<?xml version = "1.0" encoding = "UTF-8"?>
<!DOCTYPE assignments[
<!ELEMENT assignments (assignment*)>
<!ELEMENT assignment (id, deadline?, executiontime?, difficulty?, importance?)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT deadline (#PCDATA)>
<!ELEMENT executiontime (min, max)>
<!ELEMENT min (#PCDATA)>
<!ELEMENT max (#PCDATA)>
<!ELEMENT difficulty (#PCDATA)>
<!ELEMENT importance (#PCDATA)>
]>
<assignments>
    <assignment>
        <id>workReminder</id>
        <deadline>20200208</deadline>
        <executiontime>
            <min>03:50:00</min>
            <max>08:40:00</max>
        </executiontime>
        <difficulty>Very Hard</difficulty>
        <importance>Very Important</importance>
    </assignment>
    <assignment>
        <id>Tetris</id>
        <deadline>20200210</deadline>
        <executiontime>
            <min>00:05:00</min>
            <max>10:40:00</max>
        </executiontime>
        <difficulty>Very Easy</difficulty>
        <importance>Very Important</importance>
    </assignment>
</assignments>
